// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyPreview(arg1, arg2) {
  return window['go']['main']['App']['ApplyPreview'](arg1, arg2);
}

export function DetectOutputs() {
  return window['go']['main']['App']['DetectOutputs']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function ReloadKanshi() {
  return window['go']['main']['App']['ReloadKanshi']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
