// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {niri} from '../models';
import {kanshi} from '../models';

export function ApplyPreview(arg1:string,arg2:Record<string, string>):Promise<void>;

export function DetectOutputs():Promise<Array<niri.Output>>;

export function LoadConfig():Promise<kanshi.Config>;

export function ReloadKanshi():Promise<void>;

export function SaveConfig(arg1:kanshi.Config):Promise<void>;
